//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ads
    {
        public int AdID { get; set; }
        public string Username { get; set; }
        public string CategoryName { get; set; }
        public string Title { get; set; }
        public string Information { get; set; }
        public string Price { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Users Users { get; set; }
    }
}
